---
- name: Ensure swap file exists.
  ansible.builtin.command: >
    {{ swap_file_create_command }}
    creates='{{ swap_file_path }}'
  register: swap_file_create
  changed_when: swap_file_create.rc != 0

- name: Set permissions on swap file.
  ansible.builtin.file:
    path: "{{ swap_file_path }}"
    owner: root
    group: root
    mode: 0600

- name: Check if swap file exists
  ansible.builtin.stat:
    path: "{{ swap_file_path }}"
  register: swap_file_stat

- name: Create swap file if necessary
  ansible.builtin.command:
    cmd: |
      dd if=/dev/zero
      of={{ swap_file_path }}
      bs=1M
      count={{ swap_file_size_mb }}
    creates: "{{ swap_file_path }}"
  when: not swap_file_stat.stat.exists
  notify: Make swap file

- name: Set swappiness.
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "{{ swap_swappiness }}"
    state: present
