---
- name: Manage swap file entry in fstab.
  ansible.posix.mount:
    name: none
    src: "{{ swap_file_path }}"
    fstype: swap
    opts: sw
    state: "{{ swap_file_state }}"

- name: Disable tasks
  ansible.builtin.include_tasks:
    file: disable.yml
  when: swap_file_state == 'absent'

- name: Include enable tasks
  ansible.builtin.include_tasks:
    file: enable.yml
  when: swap_file_state == 'present'
